language: python
python:
  - "2.6"
  - "2.7"
virtualenv:
  system_site_packages: true


# command to prepare the system to install prerequisites or dependencies
before_install:
 - sudo apt-get -qq update
 - sudo apt-get install -qq libhdf5-serial-dev python-h5py
 - sudo apt-get install -qq libatlas-dev libatlas-base-dev gfortran
 - sudo apt-get install -qq python-numpy python-scipy python-matplotlib
 - sudo apt-get install -qq python-gst0.10 gstreamer0.10-plugins-good gstreamer0.10-gnonlin gstreamer0.10-plugins-ugly

# command to install dependencies
#install: 
# - "pip install -r requirements.txt --use-mirrors"
 - python setup.py install

# command to run tests
script:
 - py.test tests --ignore tests/sandbox
# - "python setup.py test"
