name: base
channels:
  - conda-forge
  - soumith
dependencies:
  - aubio
  - h5py
  - jsonschema
  - jupyter
  - librosa
  - matplotlib
  - mysql-python
  - networkx<2.0
  - numpy
  - pandas
  - pillow
  - python=2.7
  - python-coreapi
  - pyyaml
  - redis
  - scipy
  - simplejson
  - sphinx
  - pytables  # named tables in Pypi ...
  - pytorch
  - tensorflow
  - torchvision
  - traits
  - Werkzeug
  - yaafe
  - pip:
      - celery==3.*
      - deezer-python
      - django-bootstrap-pagination
      - django-bootstrap3
      - django-bower
      - django-celery
      - django-cors-headers
      - django-debug-toolbar
      - django-environ
      - django-extensions
      - django==1.10.*
      - djangorestframework==3.6.4
      - essentia
      - ghp-import
      - jsonfield
      - jupyterthemes
      - mutagen
      - py_sonicvisualiser==0.3
      - pympi-ling
      - sphinx_rtd_theme
      - uwsgi
      - vamp
      - watchdog
