name: timeside
channels:
  - piem
  - yaafe
dependencies:
  - aubio  # in piem channel (optionnal)
  - h5py
  - jsonschema
  - jupyter
  - matplotlib
  - mysql-python
  - networkx
  - numpy
  - pandas
  - pillow
  - python=2.7
  - pyyaml
  - redis
  - scipy
  - simplejson
  - pytables  # named tables in Pypi ...
  - traits
  - Werkzeug
  - yaafe  # in yaafe channel (optionnal)
  - pip:
      - celery==3.*
      - django-bootstrap-pagination
      - django-bootstrap3
      - django-bower
      - django-celery
      - django-cors-headers
      - django-debug-toolbar
      - django-environ
      - django-extensions
      - django==1.9.*
      - djangorestframework==3.*
      - jsonfield
      - mutagen
      - py_sonicvisualiser==0.2-9-gebe83bd
      - pympi-ling
      - uwsgi
      - watchdog
