static:
  image: debian:wheezy
  volumes:
    - /var/www/static
  command: true

log:
  image: debian:wheezy
  volumes:
    - /var/log/nginx
    - /var/log/postgres
    - /var/log/uwsgi
  command: /bin/true

lib:
  image: debian:wheezy
  volumes:
    - /var/lib/rabbitmq
    - /var/lib/postgres
    - /var/lib/mysql
  command: /bin/true

# db:
#   image: postgres
#   volumes_from:
#     - datadb

rabbitmq:
  image: rabbitmq:3-management
  ports:
    - "15672:15672"
  expose:
    - "5672"

worker:
  build: .
  volumes_from:
    - home
  command: /bin/sh /opt/TimeSide/examples/deploy/celery_app.sh
  links:
    - rabbitmq
    - app


# --- TimeSide containers ---

nginx:
  image: nginx
  ports:
    - "8000:80"
  volumes:
    - ./examples/deploy/nginx-app.conf:/etc/nginx/conf.d/default.conf
  volumes_from:
    - static
    - home
    - log
  links:
    - app

home:
  image: debian:wheezy
  volumes:
    - ./examples/sandbox:/home/timeside
  command: /bin/true

app:
  build: .
  volumes:
    - .:/opt/TimeSide
  volumes_from:
    - static
    - home
    - log
  command: /bin/sh /opt/TimeSide/examples/deploy/start_app.sh
  ports:
    - "9000:9000"
  expose:
    - "8000" #default runserver wsgi port
  links:
    - rabbitmq

