# -*- coding: utf-8 -*-
#
# Copyright (c) 2015 Parisson SARL

# This file is part of TimeSide.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.

# TimeSide is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with TimeSide.  If not, see <http://www.gnu.org/licenses/>.

# Authors:
# Guillaume Pellerin <yomguy@parisson.com>
# Thomas Fillon <thomas@parisson.com>

data:
  image: debian:jessie
  volumes:
     - ./data/media/:/srv/media
     - ./data/backup/:/srv/backup
     - /srv/static
     - /srv/bower
  command: "true"

db:
  image: mysql
  volumes:
    - ./scripts/:/srv/scripts
    - ./data/mysql/:/var/lib/mysql
  volumes_from:
    - data
  env_file:
    - env/prod.env

broker:
  image: redis

app:
  image: parisson/timeside
  volumes:
    - ./app/:/srv/app
    - ./timeside/:/srv/src/timeside/timeside
  volumes_from:
    - data
  env_file:
    - env/prod.env
  links:
    - broker
    - db
  command: /bin/bash /srv/app/scripts/app.sh

worker:
  image: parisson/timeside
  volumes:
    - ./timeside/:/srv/src/timeside/timeside
  volumes_from:
    - data
    - app
  env_file:
    - env/prod.env
  links:
    - broker
    - db
  command: /bin/bash /srv/app/scripts/worker.sh

nginx:
  image: nginx
  ports:
    - "8000:80"
  volumes:
    - ./etc/nginx.conf:/etc/nginx/conf.d/default.conf
  volumes_from:
    - app
    - data
  links:
    - app
