# -*- coding: utf-8 -*-
#
# Copyright (c) 2015 Parisson SARL

# This file is part of TimeSide.

# TimeSide is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.

# TimeSide is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with TimeSide.  If not, see <http://www.gnu.org/licenses/>.

# Authors:
# Guillaume Pellerin <yomguy@parisson.com>
# Thomas Fillon <thomas@parisson.com>


static:
  image: debian:jessie
  volumes:
    - /var/www/static
  command: "true"

log:
  image: debian:jessie
  volumes:
    - /var/log/nginx
    - /var/log/postgres
    - /var/log/uwsgi
  command: "true"

lib:
  image: debian:jessie
  volumes:
    - /var/lib/rabbitmq
    - /var/lib/postgres
    - ./var/lib/mysql:/var/lib/mysql
  command: "true"

db:
  image: mysql
  volumes_from:
    - log
    - lib
  env_file:
    - examples/sandbox/sandbox-docker.env

rabbitmq:
  image: rabbitmq:3-management
  ports:
    - "15672:15672"

nginx:
  image: nginx
  ports:
    - "8000:80"
  volumes:
    - ./examples/deploy/nginx-app.conf:/etc/nginx/conf.d/default.conf
  volumes_from:
    - app
    - static
    - log
  links:
    - app

app:
  extends:
    file: docker-compose-base.yml
    service: app
  volumes:
    - .:/opt/TimeSide
    - ./examples/sandbox:/home/sandbox
  volumes_from:
    - static
    - log
  ports:
    - "9000:9000"
  expose:
    - "8000"
  links:
    - rabbitmq
    - db

worker:
  extends:
    file: docker-compose-base.yml
    service: app
  volumes_from:
    - log
    - app
  command: /bin/bash /opt/TimeSide/examples/deploy/celery_app.sh
  links:
    - rabbitmq
    - db
