name: app
channels:
- yaafe
- piem
- defaults
dependencies:
- _nb_ext_conf=0.3.0=py27_0
- anaconda-client=1.5.2=py27_0
- backports=1.0=py27_0
- backports_abc=0.4=py27_0
- cairo=1.12.18=6
- clyent=1.2.2=py27_0
- configparser=3.5.0=py27_0
- cycler=0.10.0=py27_0
- decorator=4.0.10=py27_0
- entrypoints=0.2.2=py27_0
- enum34=1.1.6=py27_0
- fontconfig=2.11.1=6
- freetype=2.5.5=1
- functools32=3.2.3.2=py27_0
- get_terminal_size=1.0.0=py27_0
- glib=2.43.0=1
- h5py=2.6.0=np110py27_1
- harfbuzz=0.9.39=1
- hdf5=1.8.16=0
- ipykernel=4.5.0=py27_0
- ipython=5.1.0=py27_0
- ipython_genutils=0.1.0=py27_0
- ipywidgets=5.2.2=py27_0
- jbig=2.1=0
- jinja2=2.8=py27_1
- jpeg=8d=2
- jsonschema=2.5.1=py27_0
- jupyter=1.0.0=py27_3
- jupyter_client=4.4.0=py27_0
- jupyter_console=5.0.0=py27_0
- jupyter_core=4.2.0=py27_0
- libffi=3.2.1=0
- libgcc=5.2.0=0
- libgfortran=3.0.0=1
- libpng=1.6.22=0
- libsodium=1.0.10=0
- libtiff=4.0.6=2
- libxml2=2.9.2=0
- markupsafe=0.23=py27_2
- matplotlib=1.5.1=np110py27_0
- mistune=0.7.3=py27_0
- mkl=11.3.3=0
- mysql-python=1.2.5=py27_0
- nb_anacondacloud=1.2.0=py27_0
- nb_conda=2.0.0=py27_0
- nb_conda_kernels=2.0.0=py27_0
- nbconvert=4.2.0=py27_0
- nbformat=4.1.0=py27_0
- nbpresent=3.0.2=py27_0
- networkx=1.11=py27_0
- notebook=4.2.3=py27_0
- numexpr=2.5.2=np110py27_1
- numpy=1.10.4=py27_2
- openssl=1.0.2j=0
- pandas=0.18.1=np110py27_0
- pango=1.39.0=1
- path.py=8.2.1=py27_0
- pathlib2=2.1.0=py27_0
- pexpect=4.0.1=py27_0
- pickleshare=0.7.4=py27_0
- piem::aubio=0.4.2=np110py27_1
- pillow=3.4.2=py27_0
- pip=8.1.2=py27_0
- pixman=0.32.6=0
- prompt_toolkit=1.0.3=py27_0
- ptyprocess=0.5.1=py27_0
- pycairo=1.10.0=py27_0
- pygments=2.1.3=py27_0
- pyparsing=2.1.4=py27_0
- pyqt=4.11.4=py27_4
- pytables=3.2.2=np110py27_3
- python=2.7.12=1
- python-dateutil=2.5.3=py27_0
- pytz=2016.7=py27_0
- pyyaml=3.12=py27_0
- pyzmq=16.0.0=py27_0
- qt=4.8.7=4
- qtconsole=4.2.1=py27_0
- readline=6.2=2
- redis=3.2.0=0
- requests=2.11.1=py27_0
- scipy=0.17.1=np110py27_1
- setuptools=27.2.0=py27_0
- simplegeneric=0.8.1=py27_1
- simplejson=3.8.2=py27_0
- singledispatch=3.4.0.3=py27_0
- sip=4.18=py27_0
- six=1.10.0=py27_0
- sqlite=3.13.0=0
- ssl_match_hostname=3.4.0.2=py27_1
- terminado=0.6=py27_0
- tk=8.5.18=0
- tornado=4.4.2=py27_0
- traitlets=4.3.1=py27_0
- traits=4.5.0=py27_0
- wcwidth=0.1.7=py27_0
- werkzeug=0.11.11=py27_0
- wheel=0.29.0=py27_0
- widgetsnbextension=1.2.6=py27_0
- xz=5.2.2=0
- yaafe::argtable2=2.13=0
- yaafe::eigen=3.2.7=0
- yaafe::fftw=3.3.4=0
- yaafe::lapack=3.5.0=0
- yaafe::libflac=1.3.1=0
- yaafe::libmpg123=1.23.1=0
- yaafe::libogg=1.3.2=0
- yaafe::libsndfile=1.0.26=0
- yaafe::libvorbis=1.3.5=0
- yaafe::yaafe=0.70=py27_0
- yaml=0.1.6=0
- zeromq=4.1.5=0
- zlib=1.2.8=3
- pip:
  - amqp==1.4.9
  - anyjson==0.3.3
  - argh==0.26.2
  - backports-abc==0.4
  - backports.shutil-get-terminal-size==1.0.0
  - backports.ssl-match-hostname==3.4.0.2
  - billiard==3.3.0.23
  - celery==3.1.24
  - django==1.9.10
  - django-angular==0.8.4
  - django-bootstrap-pagination==1.6.2
  - django-bootstrap3==7.1.0
  - django-bower==5.2.0
  - django-celery==3.1.17
  - django-cors-headers==1.2.2
  - django-environ==0.4.0
  - django-extensions==1.7.4
  - djangorestframework==3.5.1
  - ipython-genutils==0.1.0
  - jupyter-client==4.4.0
  - jupyter-console==5.0.0
  - jupyter-core==4.2.0
  - kombu==3.0.37
  - mutagen==1.34.1
  - nb-anacondacloud==1.2.0
  - nb-conda==2.0.0
  - nb-conda-kernels==2.0.0
  - pathtools==0.1.2
  - prompt-toolkit==1.0.3
  - py-sonicvisualiser==0.2-9-gebe83bd
  - pympi-ling==1.69
  - south==1.0.2
  - tables==3.2.2
  - uwsgi==2.0.14
  - watchdog==0.8.3
